#!/bin/sh

rm server
gcc csrc/server.c -std=c99 -levent -o server
if [ "$1" != '-v' ]; then
	clear
fi
if [ -e ./server ]; then
	echo 'Compiled and built.'
else
	if [ "$1" != '-v' ]; then
		echo 'There was an error. Try running "build -v"'
	fi
fi
